@startuml

state "Das System <Systemname>" as system
state "muss | sollte | wird" as verbindlichkeit
state "fähig sein" as funktion
state "<Objekt & Objektergänzung>" as objekt
state "<Prozesswort>" as prozesswort

system --> verbindlichkeit
verbindlichkeit --> leer
funktion --> objekt
objekt -> prozesswort


@enduml